general_settings:
  block_robots: true
  store_model_in_db: true

router_settings:
  log_level: info
  num_retries: 3

litellm_settings:
  set_verbose: false
  cache: false
  add_user_id: true
  drop_params: true
